### ISSUE TITLE
Java Runtime error

### ISSUE THREAD

**Issue by Uranium2** [kitabisa/sonarqube-action#43]
I've been using version 1.2.1 since a week and it was working perfectly using a container image `owasp/dependency-check-action:latest` (last version is a month old). But since this morning I have an error regarding Java.

```yml
  sonarqube:
    runs-on: ubuntu-latest
    needs: [check_framework_version, checks_tests]
    container:
      image: owasp/dependency-check-action:latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: dependency check run
        run:
          /usr/share/dependency-check/bin/dependency-check.sh  --project "${{ env.PROJECT_NAME }}" --out "test-results/" --format "HTML" --format "XML" --format "JSON" --scan "${{ env.MY_DIR }}" --scan "${{ env.MY_TESTS_DIR }}"

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.1
        with:
          host: "https://xxxxxxxxxxxxxxx.io"
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "/home/runner/work/${{ env.MY_DIR }}/"
          projectKey: ${{ ENV.PROJECT_KEY}}
          projectVersion: ${{ env.PROJECT_VERSION }}
```

Here is the error I have.

```error
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /github/workspace/sonar-project.properties
INFO: SonarScanner 4.8.1.3023
INFO: Java 11.0.20 Alpine (64-bit)
INFO: Linux 6.5.0-10[15](https://github.com/XXXXXXXXX/actions/runs/8093791154/job/22117205565#step:8:16)-azure amd64
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Analyzing on SonarQube server 10.4.0.87286
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 6.765s
ERROR: Error during SonarScanner execution
java.lang.UnsupportedClassVersionError: org/sonar/batch/bootstrapper/EnvironmentInformation has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
INFO: Final Memory: 4M/[17](https://github.com/XXXXXXXXX/actions/runs/8093791154/job/22117205565#step:8:18)M
INFO: ------------------------------------------------------------------------
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.sonarsource.scanner.api.internal.IsolatedClassloader.loadClass(IsolatedClassloader.java:82)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at org.sonarsource.scanner.api.internal.batch.DefaultBatchFactory.createBatch(DefaultBatchFactory.java:32)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:[18](https://XXXXXXXXX/actions/runs/8093791154/job/22117205565#step:8:19)9)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:1[26](https://XXXXXXXXX/actions/runs/8093791154/job/22117205565#step:8:27))
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

Since the container image did not change, the java runtime did not change. So I don't know what happened between yesterday and today.

**Comment by markhotchkiss** [comment]
I had the same issue...I would ditch this extension and go use the official one which is what I have just done...

Here is an example of my yaml file in Github now...

`      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_USER_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        with:
          args: >
            -Dsonar.projectVersion=1.0.0
            -Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }}`
